In [1]:
pip install pytest

Note: you may need to restart the kernel to use updated packages.


 ### Theory
    * Graysclae is 2-d matrix.
    * black and white is 3-d matrix, and rbg is also 3-d matrix.

Numpy Numerical -Python
Pandas-pyton data anaylsis Libraries
#### Structured:
When Data is arranged in tabular form
e.g->RDBMS,Excel,MsAccess
    delimiter=> space,comma,semi-colons,tab
#### SemiStructured:
    json=> key value pair
    xml.xml
    xml.xml
    row<id>
#### Unstructured:
text file,pdf,docs,html
#### they have thier own staructure of storing data[Big data file formats]
These files stores data in compressed format
parquet,avro

In [26]:
# Numerical python(numpy alias as np)
import numpy as np

In [2]:
print(np.__version__)

1.21.5


In [7]:
list1 = [1,2,3,4,5,6,7,8,9]
print(type(list1))
np.array(list1)

<class 'list'>


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# N-Dimensional Array
type(np.array(list1))

numpy.ndarray

In [6]:
arr1 = np.array(list1)
arr1.dtype

dtype('int32')

In [8]:
arr1.shape

(9,)

In [9]:
arr1.ndim

1

In [10]:
print(arr1.itemsize)

4


In [11]:
print(arr1.nbytes)

36


 ## Array Operations
     * Simple Array Math Operations

In [81]:
tt = (123,'abc')
print(tt*2)

(123, 'abc', 123, 'abc')


In [82]:
d = {'a','b','c'}
print(d['b'])

TypeError: 'set' object is not subscriptable

In [85]:
a = ['a','b','c']
for i in a:
    print("n".join(i))

a
b
c


In [ ]:
l = []
?`insert()

 #### Why Numpy are better than lists

In [45]:
list2 = [10,20,30,40,50,60,70,80]
list3 = [2,4,5,6,5,8,6,2,2]

l = []
for i in range(0,len(list2)):
    l.append(list2[i]/list3[i])

In [24]:
l

[5.0, 5.0, 6.0, 6.666666666666667, 10.0, 7.5, 11.666666666666666, 40.0, 45.0]

In [26]:
for i, j in enumerate(list2):
    print(i/list3[j])

IndexError: list index out of range

In [20]:
arr3 = np.array([10,20,30,40,50,60,70,80,90])
arr4 = np.array([2,4,5,6,5,8,6,2,2])

arr3/arr4

array([ 5.        ,  5.        ,  6.        ,  6.66666667, 10.        ,
        7.5       , 11.66666667, 40.        , 45.        ])

In [36]:
np.arange(0,10,3.14)

array([0.  , 3.14, 6.28, 9.42])

In [35]:
#to generate an array of give range with steps
np.arange(0,10,2) #start stop stepsize

array([0, 2, 4, 6, 8])

### Types of Numpy Array

In [42]:
#dtype = data type with size
# int8, int 16, int32, int64
# -128 to +127 for int8 range
# if we dont mention it, by default it will be int64

In [51]:
arr1 = np.array([10,24,17,23,9,257,-128],dtype = 'int8') # int8 is used when we wanna fixed the size of our array

In [52]:
arr1

array([  10,   24,   17,   23,    9,    1, -128], dtype=int8)

In [40]:
arr1 = np.array([10,24,17,23,9,10,54,13,55,47],dtype = 'int16') # int8 is used when we wanna fixed the size of our array

In [41]:
arr2 = np.array([10.,24.,17.,23.,9.,10.,54.,13.,55.,47.],dtype = 'float16') # int8 is used when we wanna fixed the size of our array

In [46]:
list2.__sizeof__()

104

In [30]:
lt = []
for i in range(1,100,2):
    lt.append(i)

In [31]:
from functools import reduce
print(reduce(lambda x,y:x+y, lt))

2500


In [32]:
lt_temp = lt.copy()

In [33]:
def list_version(l1,l2):
    for i,j in enumerate(l1):
        print(j+l2[i])

In [28]:
def numpy_version():
    a1= np.arange(1,100,2)
    a2 = np.arange(1,100,2)
    print(a1+a2)

In [29]:
numpy_version()

[  2   6  10  14  18  22  26  30  34  38  42  46  50  54  58  62  66  70
  74  78  82  86  90  94  98 102 106 110 114 118 122 126 130 134 138 142
 146 150 154 158 162 166 170 174 178 182 186 190 194 198]


In [36]:
print(list_version(lt,lt_temp))

2
6
10
14
18
22
26
30
34
38
42
46
50
54
58
62
66
70
74
78
82
86
90
94
98
102
106
110
114
118
122
126
130
134
138
142
146
150
154
158
162
166
170
174
178
182
186
190
194
198
None


arr1[-1,-1

In [46]:
arr1 = np.array([[1,2,3,4,5,6,7,8,9],[10,20,30,40,50,60,70,80,90]])
arr1[:-1,:-1]

array([[1, 2, 3, 4, 5, 6, 7, 8]])

### Three dimentional Array

In [74]:
arr2 = np.array([[[1,2,3,4,5,6,7,8,9],[10,20,30,40,50,60,70,80,90]],
               [[11,22,33,44,55,66,77,88,99],[100,200,300,400,500,600,700,800,900]],
               [[11,12,13,14,15,16,17,18,19],[110,220,330,440,550,660,770,880,990]]])

In [75]:
arr2

array([[[  1,   2,   3,   4,   5,   6,   7,   8,   9],
        [ 10,  20,  30,  40,  50,  60,  70,  80,  90]],

       [[ 11,  22,  33,  44,  55,  66,  77,  88,  99],
        [100, 200, 300, 400, 500, 600, 700, 800, 900]],

       [[ 11,  12,  13,  14,  15,  16,  17,  18,  19],
        [110, 220, 330, 440, 550, 660, 770, 880, 990]]])

In [78]:
arr2[0][0][1:8]

array([2, 3, 4, 5, 6, 7, 8])

In [79]:
arr2[1][1][1:8]

array([200, 300, 400, 500, 600, 700, 800])

In [80]:
arr2[1][0][1:8]

array([22, 33, 44, 55, 66, 77, 88])

In [50]:
arr2.shape #rank, rows, columns

(3, 2, 9)

In [53]:
# shows length of all elements (3*2*9)
# size = number of elements present in an array
arr2.size 

54

In [55]:
arr2[1,1,4]

50

In [56]:
arr2[1][1][4]

50

### Empty array and fill it will some constact values

In [59]:
arr4 = np.empty(6,dtype = 'int16')

In [60]:
arr4

array([-28496,  10535,    557,      0,      0,      0], dtype=int16)

In [61]:
arr5 = np.arange(0,36).reshape(6,6)
arr5

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [63]:
arr5 = np.arange(0,36).reshape(3,3,4)
arr5

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

### Reverse an Array

In [64]:
arr6 = np.arange(50)
arr6[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

### Create an array using various function
    * np.ones()
    * np.zeros()

In [66]:
# shape 3 rows, 6 columns
np.ones((3,6),dtype = 'float16')

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float16)

In [67]:
np.zeros((6,6),dtype = 'float16')

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float16)

 * Identity matrix
     * generate a N x N Identity matrix. The default dtype is float64
     * Diagonal values are 1, and non diagonal values are 0

In [68]:
np.identity(7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1.]])

In [69]:
np.identity(7,dtype = 'int8')

array([[1, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 1]], dtype=int8)

In [70]:
# (start, stop, elements)
# equally spaced
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [ ]:
### Excerise: 