In [1]:
import numpy as np


### Create a 2d array with 1 on the border and rest position will zeros

In [38]:
# shape 3 rows, 6 columns
arr = np.ones((6,6),dtype = 'int16')

In [39]:
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [36]:
x = int(input("enter the number"))
x_arr = np.ones((x,x),dtype = 'int16')
s_shp = x_arr.shape[0]
for i in range(x,s_shp-1):
    if i > s_shp-1:
        x_arr[i-s_shp+1][1:(i-1)] = 0


enter the number4


In [47]:
arr[1:-1,1:-1] = 0

In [48]:
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [8]:
arr[1][1:5] = 0
arr[2][1:5] = 0
arr[3][1:5] = 0
arr[4][1:5] = 0
#arr[][1:5] = 0

In [34]:
arr

array([[1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [25]:
arr3 = np.ones((3,6),dtype = 'int16')

In [26]:
arr3

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int16)

In [27]:
arr3[0][1] = 0
arr3[0][3] = 0
arr3[0][5] = 0
arr3[1][0] = 0
arr3[1][2] = 0
arr3[1][4] = 0
arr3[2][1] = 0
arr3[2][3] = 0
arr3[2][5] = 0

### Create a CheckerBoard (Chess Board

In [55]:
arr4 = np.ones((10,10),dtype = 'int16')
arr4[1::2,0::2] = 0
arr4[0::2,1::2] = 0

In [56]:
arr4

array([[1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1, 0, 1]], dtype=int16)

In [59]:
arr5 = arr4[0::2,0::2] #extracting ones only from arr4 

In [58]:
arr5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int16)

### Null Values

In [60]:
# nan - not a number
arr6 = np.ones((10,10))
arr6[1::2,0::2] = np.nan
arr6[0::2,1::2] = np.nan
arr6

array([[ 1., nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan,  1.],
       [ 1., nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan,  1.],
       [ 1., nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan,  1.],
       [ 1., nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan,  1.],
       [ 1., nan,  1., nan,  1., nan,  1., nan,  1., nan],
       [nan,  1., nan,  1., nan,  1., nan,  1., nan,  1.]])

In [63]:
# isnan() - returns boolean value, True for missing data, False for not missing data
np.isnan(arr6) 

array([[False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False],
       [False,  True, False,  True, False,  True, False,  True, False,
         True],
       [ True, False,  True, False,  True, False,  True, False,  True,
        False]])

In [66]:
# np.count_nonzero() count False/0 values
np.count_nonzero(~np.isnan(arr6))

50

In [4]:
import numpy as np
arr7 = np.array([['a','b','c','d'],
       ['e','f','g','h'],
       ['i','j','k','l'],
       ['m','n','o','p'],
       ['q','r','s','t'],
       ['u','v','w','x']])

In [2]:
arr7.shape

AttributeError: 'list' object has no attribute 'shape'

In [146]:
count = 0
for i in range(0,6):
    for j in range(0,4):
        if arr7[i][j] in list1:
            print(arr7[i][j])
            arr7[i][j] = False
            count += 1

a
e
i
o
u


In [147]:
arr7

[[False, 'b', 'c', 'd'],
 [False, 'f', 'g', 'h'],
 [False, 'j', 'k', 'l'],
 ['m', 'n', False, 'p'],
 ['q', 'r', 's', 't'],
 [False, 'v', 'w', 'x']]

In [141]:
arr7 = np.array([['a','b','c','d'],
       ['e','f','g','h'],
       ['i','j','k','l'],
       ['m','n','o','p'],
       ['q','r','s','t'],
       ['u','v','w','x']])

In [ ]:
arr7 = np.array([['a','b','c','d'],
       ['e','f','g','h'],
       ['i','j','k','l'],
       ['m','n','o','p'],
       ['q','r','s','t'],
       ['u','v','w','x']])



In [142]:
arr7.shape

(6, 4)

In [143]:
list1 = ['a','e','i','o','u']

In [ ]:
for i in  

In [144]:
for i in range(0,6):
    for j in range(0,4):
        if arr7[i][j] in list1:
            print(arr7[i][j])
            arr7[i][j] = '?'

a
e
i
o
u


In [139]:
arr7

array([['?', 'b', 'c', 'd'],
       ['?', 'f', 'g', 'h'],
       ['?', 'j', 'k', 'l'],
       ['m', 'n', '?', 'p'],
       ['q', 'r', 's', 't'],
       ['?', 'v', 'w', 'x']], dtype='<U1')

In [140]:
count = 0
for i in range(0,6):
    for j in range(0,4):
        if arr7[i][j] == '?':
            count = count +1
print(count)

5


### Reversing of an array

In [149]:
arr8 = np.arange(50)
arr8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [150]:
arr8[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [152]:
arr9 = np.arange(0,36).reshape(6,6)
arr9

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [162]:
# up() -> up/down
print(arr9)
np.flipud(arr9) #rows will interchange


[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[30, 31, 32, 33, 34, 35],
       [24, 25, 26, 27, 28, 29],
       [18, 19, 20, 21, 22, 23],
       [12, 13, 14, 15, 16, 17],
       [ 6,  7,  8,  9, 10, 11],
       [ 0,  1,  2,  3,  4,  5]])

In [160]:
# lr() - left/right
print(arr9)
np.fliplr(arr9) #column will inter change

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[ 5,  4,  3,  2,  1,  0],
       [11, 10,  9,  8,  7,  6],
       [17, 16, 15, 14, 13, 12],
       [23, 22, 21, 20, 19, 18],
       [29, 28, 27, 26, 25, 24],
       [35, 34, 33, 32, 31, 30]])

In [159]:
# to flip both rows and columns
print(arr9)
np.flip(arr9)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


array([[35, 34, 33, 32, 31, 30],
       [29, 28, 27, 26, 25, 24],
       [23, 22, 21, 20, 19, 18],
       [17, 16, 15, 14, 13, 12],
       [11, 10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1,  0]])

In [167]:
temp = [[1,2,3],[4,5,6]]

In [168]:
type(temp)

list

In [163]:
arr10 = np.array([[1,2,3],
                 [4,5,6]])
arr10

array([[1, 2, 3],
       [4, 5, 6]])

In [164]:
arr10.sum()

21

In [165]:
# row1 + row2
# apply sum() along 8th axis
arr10.sum(axis = 0)

array([5, 7, 9])

In [166]:
# column1 + column2
arr10.sum(axis=1)

array([ 6, 15])

In [169]:
arr10.min()

1

In [171]:
# argmax used to get the index of max element
print(arr10)
np.argmax(arr10)

[[1 2 3]
 [4 5 6]]


5

In [174]:
arr11 = np.arange(0,36).reshape(6,6)
arr11

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [175]:
arr11.argmax(arr11)

TypeError: only integer scalar arrays can be converted to a scalar index

In [176]:
np.median(arr11)

17.5

In [177]:
np.std(arr11)

10.388294694831615

In [178]:
np.var(arr11)

107.91666666666667

In [ ]:
au