1.	Create a python program to find duplicate files by content. User will input path and it will scan all directories, sub-directories to find all duplicates files.
Delete the found duplicate file.
[Hint: use hashlib]


In [51]:
import os
import hashlib

def get_files(path):
    """
    This function takes a path as input and returns a list of all the files in that path and its subdirectories.
    """
    files = []
    for dirpath, _, filenames in os.walk(path):
        for filename in filenames:
            files.append(os.path.join(dirpath, filename))
    return files

def get_file_hash(file_path):
    """
    This function takes a file path as input and returns the SHA-256 hash of the file's contents.
    """
    with open(file_path, "rb") as f:
        file_hash = hashlib.sha256()
        while chunk := f.read(8192):
            file_hash.update(chunk)
        return file_hash.digest()

def find_duplicates(path):
    """
    This function takes a path as input and finds all the duplicate files by content.
    """
    hashes = {}
    duplicates = []
    files = get_files(path)
    for file_path in files:
        file_hash = get_file_hash(file_path)
        if file_hash in hashes:
            duplicates.append(file_path)
        else:
            hashes[file_hash] = file_path
    return duplicates

def delete_duplicates(duplicates):
    """
    This function takes a list of duplicate file paths as input and deletes them.
    """
    for file_path in duplicates:
        os.remove(file_path)

if __name__ == "__main__":
    path = input("Enter path to search for duplicates: ")
    duplicates = find_duplicates(path)
    if len(duplicates) > 0:
        print("Found duplicates:")
        for file_path in duplicates:
            print(file_path)
        delete = input("Do you want to delete the duplicates? (y/n) ")
        if delete.lower() == "y":
            delete_duplicates(duplicates)
            print("Duplicates deleted.")
        else:
            print("Duplicates not deleted.")
    else:
        print("No duplicates found.")


Enter path to search for duplicates: D:\testing
Found duplicates:
D:\testing\python\file2.txt
D:\testing\python\python-2\file3.txt
D:\testing\sql\sql2.txt
Do you want to delete the duplicates? (y/n) y
Duplicates deleted.


2. Generate random Password with exact length = 6, with minimum 1 uppercase, 2 lowercase, 2 digits, and remaining special characters.
Using these packages [random, strings]


In [5]:
import random
import string
n1 = random.randint(0, 9)
n2 = random.randint(0, 9)
s3 = random.choice(string.punctuation)
l1 = random.choice(string.ascii_lowercase)
l2 = random.choice(string.ascii_lowercase)
u1 = random.choice(string.ascii_uppercase)
neel_password = [str(n1),str(n2),s3,l1,l2,u1]
random.shuffle(neel_password)
secret_password = ""
for i in neel_password:
    secret_password+=i

In [6]:
secret_password

'\\eU2r2'

3.	Create 2D array and update the same 2D array provided that every prime number position should be replaced by cube of the positioned number.

In [56]:
import numpy as np
arr = np.array([[1,2,3,4],[5,6,7,8]])
arr
arr.shape
a =[]
# flag= 0
# n=29
a =[]
def is_prime(n):
    if n<2:
        return False
    for i in range(2,n):
        if n%i==0:
            return False
    return True
arr_3 =arr.reshape(8)
print(arr_3)
a=arr_3.tolist()
b=[]
for i in a:
    if is_prime(i)==True:
        b.append(a.index(i))
print(b)
for i in range(arr.shape[0]):
    for j in range(arr.shape[1]):
        if is_prime(arr[i][j]):
#             a.append(i)
            arr[i,j] = (arr[i][j])**3
print(arr)
print(a)

[1 2 3 4 5 6 7 8]
[1, 2, 4, 6]
[[  1   8  27   4]
 [125   6 343   8]]
[1, 2, 3, 4, 5, 6, 7, 8]


4.	Python program to get the sum of every cubed value and its previous integer. 

In [57]:
print(arr)
new_array=arr.reshape(8)
new_array

[[  1   8  27   4]
 [125   6 343   8]]


array([  1,   8,  27,   4, 125,   6, 343,   8])

In [58]:
for i in b:
    new_array[i]=new_array[i]+new_array[i-1]
# print(new_array)
final_array = new_array.reshape(2,4)
# print(final_array)
my_array = np.asarray(final_array)
my_array

array([[  1,   9,  36,   4],
       [129,   6, 349,   8]])

In [ ]:
5.	Given two arrays, find their intersection. Examples:

Input:  arr1[] = [1, 3, 4, 5, 7]
             arr2[] = [2, 3, 5, 6]


In [8]:
import numpy as np
arr1 = np.array([1, 3, 4, 5, 7])
arr2 = np.array([2, 3, 5, 6])

intersection = np.intersect1d(arr1,arr2)
print(intersection)

[3 5]


  6.	Create a 7 x 7  2D array having only multiples of 7. And return the last element of the same.

In [24]:
arr4 = np.arange(7,344,7).reshape(7,7)

In [27]:
print(arr4.shape)
print(arr4)

(7, 7)
[[  7  14  21  28  35  42  49]
 [ 56  63  70  77  84  91  98]
 [105 112 119 126 133 140 147]
 [154 161 168 175 182 189 196]
 [203 210 217 224 231 238 245]
 [252 259 266 273 280 287 294]
 [301 308 315 322 329 336 343]]


In [28]:
arr4[6][6]

343

In [ ]:
7.	Checker Board Patten using Numpy:
[   1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1
    0   1   0   1   0   1   0
    1   0   1   0   1   0   1  ]


In [31]:
arr5 = np.ones((5,7),dtype = 'int16')
arr5[1::2,0::2] = 0
arr5[0::2,1::2] = 0

In [32]:
print(arr5)

[[1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]]


In [ ]:
8.	Create a given Matrix:
[  A,     B,     C,       D
   E,      F,     G,       H
    I,      a,      K,       L
   M,    N,     o,       P
   Q,     R,      S,       T
   U,     0,     W,      O ]

Replace all the vowels by np.nan
A, E, I, O U  -- >  np.nan
Return the count of the missing values


In [46]:
arr6 = ['A','B','C','D',
       'E','F','G','H',
       'I','A','K','L',
       'M','N','O','P',
       'Q','R','S','T',
       'U',0,'W','O']


In [47]:
vovl = ['A','E','I','O','U']

In [48]:
for i in range(0,len(arr6)):
    if arr6[i] in vovl:
        arr6[i] = False
    if arr6[i] == False:
        arr6[i] = False
        

In [50]:
arr6.count(False)

8