In [1]:
import sqlalchemy

In [13]:
import numpy as np
import pandas as pd
import sklearn


In [3]:
import sqlite3
import dask


In [ ]:
from dask import array

In [4]:
a =  np.array([1,2,3,4,5]) #datastructure used in that particular 
a.dtype

dtype('int32')

In [5]:
type(a) #python fucntion

numpy.ndarray

In [7]:
np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [17]:
# generating random sample of gicen diemntions
# Note random number are generated between 0 to 1. multiply them with an appropiate factor to get required outcome
np.random.random_sample((3,2))*10

array([[3.67699827, 0.10103931],
       [8.27616312, 6.86931538],
       [5.4723071 , 8.66785856]])

In [9]:
#inspecting dimentions for the array
a.shape

(5,)

In [15]:
np.random.random_integers(1,10)

C:\Users\neroy\AppData\Local\Temp\ipykernel_5348\1904809868.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  np.random.random_integers(1,10)


6

In [16]:
np.random.randint(1,10+1)

4

In [28]:
#matrix multiplication
s = np.array([1,2])
t = np.array([[10,20,30,40],[100,200,300,400]])
print(s.shape)
print(t.shape)

(2,)
(2, 4)


In [25]:
a1 = np.array([10,20,30,40,50])
print(a1[::-1])

[50 40 30 20 10]


In [33]:
a2 = np.array([[10,20,30,40],[20,40,60,80]])
print(a2)

[[10 20 30 40]
 [20 40 60 80]]


In [59]:
print(a2[::-1,::-1])

[[80 60 40 20]
 [40 30 20 10]]


In [43]:
#kadd two big vector
import time 
size_of_vec = 100000
t1 = time.time()
x = range(size_of_vec)
y = range(size_of_vec)
z_list = []
for i in range(len(x)):
    z_list.append(x[i]+y[i])
time.time() - t1

0.05026865005493164

In [44]:
t1 = time.time()
x = np.arange(size_of_vec)
y = np.arange(size_of_vec)
z_numpy = x+y
float(time.time() - t1)

0.002550363540649414

In [45]:
z_list == z_numpy

array([ True,  True,  True, ...,  True,  True,  True])

## Broadcasting
Broadcasting is a powerful mechanism that allows numpy to work with arrays to different shapes when performing arithmetic operations frequently we have a smaller array and a larger array and we want to  use the smaller array multiple times to perform some operations on the larger array

In [47]:
# we will add the vector v to each row of the matrix x,
# stroing the result in the matrix y
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
y = x +v # add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [50]:
x = np.array([1,2,3,4,5,6], dtype = np.int32)
y = x[::-2]
y

array([6, 4, 2])

In [51]:
y.strides


(-8,)

In [60]:
x = np.zeros((10,10,10), dtype=np.float)
x.strides
#x[::2,::3,::4].strides

C:\Users\neroy\AppData\Local\Temp\ipykernel_5348\4167669816.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.zeros((10,10,10), dtype=np.float)


(800, 80, 8)

In [61]:
a = np.arange(6,dtype=np.int8).reshape(3,2)
b = a.T
b.strides

(1, 2)

In [63]:
np.random.seed(2345)
marks = np.random.randint(20,100,size=(4,6))
print(marks)
print("minimum marks in the subject ", marks.min(axis=0))
print("maximum marks in the subject ", marks.max(axis=0))
print("total marks in the subject ", marks.sum(axis=1))

[[27 36 22 20 98 71]
 [89 87 32 44 69 47]
 [76 24 99 71 45 35]
 [27 69 24 65 23 36]]
minimum marks in the subject  [27 24 22 20 23 35]
maximum marks in the subject  [89 87 99 71 98 71]
total marks in the subject  [274 368 350 244]


In [3]:
from sklearn import datasets
iris = datasets.load_iris()
x = iris.data

In [4]:
print(x)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [5]:
type(x)

numpy.ndarray

In [6]:
x.dtype

dtype('float64')

In [7]:
x.shape

(150, 4)

In [8]:
petal_data = x[100:141,2:]

In [9]:
petal_data.shape

(41, 2)

In [10]:
petal_data

array([[6. , 2.5],
       [5.1, 1.9],
       [5.9, 2.1],
       [5.6, 1.8],
       [5.8, 2.2],
       [6.6, 2.1],
       [4.5, 1.7],
       [6.3, 1.8],
       [5.8, 1.8],
       [6.1, 2.5],
       [5.1, 2. ],
       [5.3, 1.9],
       [5.5, 2.1],
       [5. , 2. ],
       [5.1, 2.4],
       [5.3, 2.3],
       [5.5, 1.8],
       [6.7, 2.2],
       [6.9, 2.3],
       [5. , 1.5],
       [5.7, 2.3],
       [4.9, 2. ],
       [6.7, 2. ],
       [4.9, 1.8],
       [5.7, 2.1],
       [6. , 1.8],
       [4.8, 1.8],
       [4.9, 1.8],
       [5.6, 2.1],
       [5.8, 1.6],
       [6.1, 1.9],
       [6.4, 2. ],
       [5.6, 2.2],
       [5.1, 1.5],
       [5.6, 1.4],
       [6.1, 2.3],
       [5.6, 2.4],
       [5.5, 1.8],
       [4.8, 1.8],
       [5.4, 2.1],
       [5.6, 2.4]])

In [19]:
a = np.array([1,2,3,4,5,6,7,8,9,10,11])
np.append(a,65) #append doesnt make the changes in the array
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11]


In [20]:
b = np.append(a,65)
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 65])

In [22]:
c1 = b.reshape(3,4)
c1 = np.append(c1,[[11,12,13,14]],axis =0) #adding number of rows
#c1
print(c1)
c2 = b.reshape(3,4)
c2 = np.append(c2,[[31],[32],[33]],axis = 1) #adding number of columns
print(c2)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 65]
 [11 12 13 14]]
[[ 1  2  3  4 31]
 [ 5  6  7  8 32]
 [ 9 10 11 65 33]]


In [23]:
arr1 = np.array([[101,102],[103,104]])
print(np.insert(arr1,1,[111,112],axis =0))
np.insert(arr1,1,[111,112],axis=1)

[[101 102]
 [111 112]
 [103 104]]


array([[101, 111, 102],
       [103, 112, 104]])

In [27]:
a = np.array([[1,2],[3,4],[5,6]])
print(a)
print(a[[0,1,2],[0,1,0]])

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [28]:
print(np.array([a[0,0],a[1,1], a[2,0]]))

[1 4 5]


In [30]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
#create an array of indices
b = np.array([0,2,0,1])

#select one element form each row of a using the indices in b
print(a[np.arange(4),b])

[ 1  6  7 11]


In [31]:
print(np.arange(4))

[0 1 2 3]
